//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region AuditAuditor
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AuditAuditor :
        global::LightSwitchApplication.AuditAuditor.DetailsClass.IImplementation
    {
        partial void OnAuditAuditor_AuditChanged()
        {
            this.___OnPropertyChanged("AuditAuditor_Audit");
            this.___OnPropertyChanged("Audit");
        }
        
        partial void OnAuditAuditor_AuditorChanged()
        {
            this.___OnPropertyChanged("AuditAuditor_Auditor");
            this.___OnPropertyChanged("Auditor");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AuditAuditor.DetailsClass.IImplementation.Audit
        {
            get
            {
                return this.Audit;
            }
            set
            {
                this.Audit = (global::LightSwitchApplication.Implementation.Audit)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Audit> __Audit
        {
            get
            {
                if (this.___Audit == null)
                {
                    this.___Audit = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Audit>(
                        this,
                        "Audit",
                        new string[] { "AuditAuditor_Audit" },
                        e => global::System.Object.Equals(e.Id, this.AuditAuditor_Audit),
                        () => this._Audit,
                        e => this._Audit = e);
                }
                return this.___Audit;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Audit> ___Audit;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AuditAuditor.DetailsClass.IImplementation.Auditor
        {
            get
            {
                return this.Auditor;
            }
            set
            {
                this.Auditor = (global::LightSwitchApplication.Implementation.Auditor)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Auditor> __Auditor
        {
            get
            {
                if (this.___Auditor == null)
                {
                    this.___Auditor = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Auditor>(
                        this,
                        "Auditor",
                        new string[] { "AuditAuditor_Auditor" },
                        e => global::System.Object.Equals(e.Id, this.AuditAuditor_Auditor),
                        () => this._Auditor,
                        e => this._Auditor = e);
                }
                return this.___Auditor;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Auditor> ___Auditor;
        
    }
    #endregion
    
    #region AuditFinding
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AuditFinding :
        global::LightSwitchApplication.AuditFinding.DetailsClass.IImplementation
    {
        partial void OnAuditFinding_EmployeeChanged()
        {
            this.___OnPropertyChanged("AuditFinding_Employee");
            this.___OnPropertyChanged("AssignedTo");
        }
        
        partial void OnAuditFinding_AuditChanged()
        {
            this.___OnPropertyChanged("AuditFinding_Audit");
            this.___OnPropertyChanged("Audit");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnFindingReferenceChanged()
        {
            this.___OnPropertyChanged("FindingReference");
        }
        
        partial void OnFindingDescriptionChanged()
        {
            this.___OnPropertyChanged("FindingDescription");
        }
        
        partial void OnFindingDateChanged()
        {
            this.___OnPropertyChanged("FindingDate");
        }
        
        partial void OnTargetResolutionDateChanged()
        {
            this.___OnPropertyChanged("TargetResolutionDate");
        }
        
        partial void OnFindingImpactAssessmentChanged()
        {
            this.___OnPropertyChanged("FindingImpactAssessment");
        }
        
        partial void OnImmediateActionChanged()
        {
            this.___OnPropertyChanged("ImmediateAction");
        }
        
        partial void OnCorrectiveAndPreventativeActionChanged()
        {
            this.___OnPropertyChanged("CorrectiveAndPreventativeAction");
        }
        
        partial void OnCorrectiveAndPreventativeActionTargetDateChanged()
        {
            this.___OnPropertyChanged("CorrectiveAndPreventativeActionTargetDate");
        }
        
        partial void OnDateCorrectiveAndPreventativeActionClosedChanged()
        {
            this.___OnPropertyChanged("DateCorrectiveAndPreventativeActionClosed");
        }
        
        partial void OnDateFindingClosedChanged()
        {
            this.___OnPropertyChanged("DateFindingClosed");
        }
        
        partial void OnNotesChanged()
        {
            this.___OnPropertyChanged("Notes");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AuditFinding.DetailsClass.IImplementation.AssignedTo
        {
            get
            {
                return this.AssignedTo;
            }
            set
            {
                this.AssignedTo = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __AssignedTo
        {
            get
            {
                if (this.___AssignedTo == null)
                {
                    this.___AssignedTo = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "AssignedTo",
                        new string[] { "AuditFinding_Employee" },
                        e => global::System.Object.Equals(e.Id, this.AuditFinding_Employee),
                        () => this._AssignedTo,
                        e => this._AssignedTo = e);
                }
                return this.___AssignedTo;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___AssignedTo;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.AuditFinding.DetailsClass.IImplementation.FindingAction
        {
            get
            {
                return this.FindingAction;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.FindingAction> __FindingAction
        {
            get
            {
                if (this.___FindingAction == null)
                {
                    this.___FindingAction = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.FindingAction>(
                        this,
                        "FindingAction",
                        () => this._FindingAction,
                        e => global::System.Object.Equals(e.IssueAction_AuditFinding, this.Id));
                }
                return this.___FindingAction;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.FindingAction> ___FindingAction;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AuditFinding.DetailsClass.IImplementation.Audit
        {
            get
            {
                return this.Audit;
            }
            set
            {
                this.Audit = (global::LightSwitchApplication.Implementation.Audit)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Audit> __Audit
        {
            get
            {
                if (this.___Audit == null)
                {
                    this.___Audit = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Audit>(
                        this,
                        "Audit",
                        new string[] { "AuditFinding_Audit" },
                        e => global::System.Object.Equals(e.Id, this.AuditFinding_Audit),
                        () => this._Audit,
                        e => this._Audit = e);
                }
                return this.___Audit;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Audit> ___Audit;
        
    }
    #endregion
    
    #region Auditor
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Auditor :
        global::LightSwitchApplication.Auditor.DetailsClass.IImplementation
    {
        partial void OnAuditor_EmployeeChanged()
        {
            this.___OnPropertyChanged("Auditor_Employee");
            this.___OnPropertyChanged("Employee");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnDateTrainedChanged()
        {
            this.___OnPropertyChanged("DateTrained");
        }
        
        partial void OnCurrentAuditorChanged()
        {
            this.___OnPropertyChanged("CurrentAuditor");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Auditor.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __Employee
        {
            get
            {
                if (this.___Employee == null)
                {
                    this.___Employee = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Employee",
                        new string[] { "Auditor_Employee" },
                        e => global::System.Object.Equals(e.Id, this.Auditor_Employee),
                        () => this._Employee,
                        e => this._Employee = e);
                }
                return this.___Employee;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___Employee;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Auditor.DetailsClass.IImplementation.AuditAuditors
        {
            get
            {
                return this.AuditAuditors;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AuditAuditor> __AuditAuditors
        {
            get
            {
                if (this.___AuditAuditors == null)
                {
                    this.___AuditAuditors = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AuditAuditor>(
                        this,
                        "AuditAuditors",
                        () => this._AuditAuditors,
                        e => global::System.Object.Equals(e.AuditAuditor_Auditor, this.Id));
                }
                return this.___AuditAuditors;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AuditAuditor> ___AuditAuditors;
        
    }
    #endregion
    
    #region Audit
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Audit :
        global::LightSwitchApplication.Audit.DetailsClass.IImplementation
    {
        partial void OnAuditType_AuditChanged()
        {
            this.___OnPropertyChanged("AuditType_Audit");
            this.___OnPropertyChanged("AuditType");
        }
        
        partial void OnAuditStatus_AuditChanged()
        {
            this.___OnPropertyChanged("AuditStatus_Audit");
            this.___OnPropertyChanged("AuditStatus");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnAuditCodeChanged()
        {
            this.___OnPropertyChanged("AuditCode");
        }
        
        partial void OnAuditDescriptionChanged()
        {
            this.___OnPropertyChanged("AuditDescription");
        }
        
        partial void OnSchduledDateChanged()
        {
            this.___OnPropertyChanged("SchduledDate");
        }
        
        partial void OnDateStartedChanged()
        {
            this.___OnPropertyChanged("DateStarted");
        }
        
        partial void OnDateCompletedChanged()
        {
            this.___OnPropertyChanged("DateCompleted");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Audit.DetailsClass.IImplementation.AuditType
        {
            get
            {
                return this.AuditType;
            }
            set
            {
                this.AuditType = (global::LightSwitchApplication.Implementation.AuditType)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AuditType> __AuditType
        {
            get
            {
                if (this.___AuditType == null)
                {
                    this.___AuditType = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AuditType>(
                        this,
                        "AuditType",
                        new string[] { "AuditType_Audit" },
                        e => global::System.Object.Equals(e.Id, this.AuditType_Audit),
                        () => this._AuditType,
                        e => this._AuditType = e);
                }
                return this.___AuditType;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AuditType> ___AuditType;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Audit.DetailsClass.IImplementation.AuditStatus
        {
            get
            {
                return this.AuditStatus;
            }
            set
            {
                this.AuditStatus = (global::LightSwitchApplication.Implementation.AuditStatus)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AuditStatus> __AuditStatus
        {
            get
            {
                if (this.___AuditStatus == null)
                {
                    this.___AuditStatus = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AuditStatus>(
                        this,
                        "AuditStatus",
                        new string[] { "AuditStatus_Audit" },
                        e => global::System.Object.Equals(e.Id, this.AuditStatus_Audit),
                        () => this._AuditStatus,
                        e => this._AuditStatus = e);
                }
                return this.___AuditStatus;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AuditStatus> ___AuditStatus;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Audit.DetailsClass.IImplementation.AuditAuditors
        {
            get
            {
                return this.AuditAuditors;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AuditAuditor> __AuditAuditors
        {
            get
            {
                if (this.___AuditAuditors == null)
                {
                    this.___AuditAuditors = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AuditAuditor>(
                        this,
                        "AuditAuditors",
                        () => this._AuditAuditors,
                        e => global::System.Object.Equals(e.AuditAuditor_Audit, this.Id));
                }
                return this.___AuditAuditors;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AuditAuditor> ___AuditAuditors;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Audit.DetailsClass.IImplementation.AuditFindings
        {
            get
            {
                return this.AuditFindings;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AuditFinding> __AuditFindings
        {
            get
            {
                if (this.___AuditFindings == null)
                {
                    this.___AuditFindings = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AuditFinding>(
                        this,
                        "AuditFindings",
                        () => this._AuditFindings,
                        e => global::System.Object.Equals(e.AuditFinding_Audit, this.Id));
                }
                return this.___AuditFindings;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AuditFinding> ___AuditFindings;
        
    }
    #endregion
    
    #region AuditStatus
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AuditStatus :
        global::LightSwitchApplication.AuditStatus.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnAuditStatusDescriptionChanged()
        {
            this.___OnPropertyChanged("AuditStatusDescription");
        }
        
        partial void OnInUseChanged()
        {
            this.___OnPropertyChanged("InUse");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.AuditStatus.DetailsClass.IImplementation.Audits
        {
            get
            {
                return this.Audits;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Audit> __Audits
        {
            get
            {
                if (this.___Audits == null)
                {
                    this.___Audits = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Audit>(
                        this,
                        "Audits",
                        () => this._Audits,
                        e => global::System.Object.Equals(e.AuditStatus_Audit, this.Id));
                }
                return this.___Audits;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Audit> ___Audits;
        
    }
    #endregion
    
    #region AuditType
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AuditType :
        global::LightSwitchApplication.AuditType.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnAuditTypeDescriptionChanged()
        {
            this.___OnPropertyChanged("AuditTypeDescription");
        }
        
        partial void OninUseChanged()
        {
            this.___OnPropertyChanged("inUse");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.AuditType.DetailsClass.IImplementation.Audits
        {
            get
            {
                return this.Audits;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Audit> __Audits
        {
            get
            {
                if (this.___Audits == null)
                {
                    this.___Audits = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Audit>(
                        this,
                        "Audits",
                        () => this._Audits,
                        e => global::System.Object.Equals(e.AuditType_Audit, this.Id));
                }
                return this.___Audits;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Audit> ___Audits;
        
    }
    #endregion
    
    #region Employee
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnLastNameChanged()
        {
            this.___OnPropertyChanged("LastName");
        }
        
        partial void OnFirstNameChanged()
        {
            this.___OnPropertyChanged("FirstName");
        }
        
        partial void OnUserNameChanged()
        {
            this.___OnPropertyChanged("UserName");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnCurrentChanged()
        {
            this.___OnPropertyChanged("Current");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.Auditors
        {
            get
            {
                return this.Auditors;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Auditor> __Auditors
        {
            get
            {
                if (this.___Auditors == null)
                {
                    this.___Auditors = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Auditor>(
                        this,
                        "Auditors",
                        () => this._Auditors,
                        e => global::System.Object.Equals(e.Auditor_Employee, this.Id));
                }
                return this.___Auditors;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Auditor> ___Auditors;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.AuditFindings
        {
            get
            {
                return this.AuditFindings;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AuditFinding> __AuditFindings
        {
            get
            {
                if (this.___AuditFindings == null)
                {
                    this.___AuditFindings = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AuditFinding>(
                        this,
                        "AuditFindings",
                        () => this._AuditFindings,
                        e => global::System.Object.Equals(e.AuditFinding_Employee, this.Id));
                }
                return this.___AuditFindings;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AuditFinding> ___AuditFindings;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.FindingAction
        {
            get
            {
                return this.FindingAction;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.FindingAction> __FindingAction
        {
            get
            {
                if (this.___FindingAction == null)
                {
                    this.___FindingAction = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.FindingAction>(
                        this,
                        "FindingAction",
                        () => this._FindingAction,
                        e => global::System.Object.Equals(e.IssueAction_Employee, this.Id));
                }
                return this.___FindingAction;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.FindingAction> ___FindingAction;
        
    }
    #endregion
    
    #region FindingAction
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class FindingAction :
        global::LightSwitchApplication.FindingAction.DetailsClass.IImplementation
    {
        partial void OnIssueAction_EmployeeChanged()
        {
            this.___OnPropertyChanged("IssueAction_Employee");
            this.___OnPropertyChanged("AssignedTo");
        }
        
        partial void OnIssueAction_AuditFindingChanged()
        {
            this.___OnPropertyChanged("IssueAction_AuditFinding");
            this.___OnPropertyChanged("AuditFinding");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnActionChanged()
        {
            this.___OnPropertyChanged("Action");
        }
        
        partial void OnActionCommentChanged()
        {
            this.___OnPropertyChanged("ActionComment");
        }
        
        partial void OnDateActionAssignedChanged()
        {
            this.___OnPropertyChanged("DateActionAssigned");
        }
        
        partial void OnActionTargetCompletionDateChanged()
        {
            this.___OnPropertyChanged("ActionTargetCompletionDate");
        }
        
        partial void OnDateActionCompletedChanged()
        {
            this.___OnPropertyChanged("DateActionCompleted");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.FindingAction.DetailsClass.IImplementation.AssignedTo
        {
            get
            {
                return this.AssignedTo;
            }
            set
            {
                this.AssignedTo = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __AssignedTo
        {
            get
            {
                if (this.___AssignedTo == null)
                {
                    this.___AssignedTo = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "AssignedTo",
                        new string[] { "IssueAction_Employee" },
                        e => global::System.Object.Equals(e.Id, this.IssueAction_Employee),
                        () => this._AssignedTo,
                        e => this._AssignedTo = e);
                }
                return this.___AssignedTo;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___AssignedTo;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.FindingAction.DetailsClass.IImplementation.AuditFinding
        {
            get
            {
                return this.AuditFinding;
            }
            set
            {
                this.AuditFinding = (global::LightSwitchApplication.Implementation.AuditFinding)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AuditFinding> __AuditFinding
        {
            get
            {
                if (this.___AuditFinding == null)
                {
                    this.___AuditFinding = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AuditFinding>(
                        this,
                        "AuditFinding",
                        new string[] { "IssueAction_AuditFinding" },
                        e => global::System.Object.Equals(e.Id, this.IssueAction_AuditFinding),
                        () => this._AuditFinding,
                        e => this._AuditFinding = e);
                }
                return this.___AuditFinding;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.AuditFinding> ___AuditFinding;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.AuditAuditor))
            {
                return new global::LightSwitchApplication.Implementation.AuditAuditor();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AuditFinding))
            {
                return new global::LightSwitchApplication.Implementation.AuditFinding();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Auditor))
            {
                return new global::LightSwitchApplication.Implementation.Auditor();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Audit))
            {
                return new global::LightSwitchApplication.Implementation.Audit();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AuditStatus))
            {
                return new global::LightSwitchApplication.Implementation.AuditStatus();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AuditType))
            {
                return new global::LightSwitchApplication.Implementation.AuditType();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.FindingAction))
            {
                return new global::LightSwitchApplication.Implementation.FindingAction();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.AuditAuditor) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AuditAuditor);
            }
            if (typeof(global::LightSwitchApplication.AuditFinding) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AuditFinding);
            }
            if (typeof(global::LightSwitchApplication.Auditor) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Auditor);
            }
            if (typeof(global::LightSwitchApplication.Audit) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Audit);
            }
            if (typeof(global::LightSwitchApplication.AuditStatus) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AuditStatus);
            }
            if (typeof(global::LightSwitchApplication.AuditType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AuditType);
            }
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            if (typeof(global::LightSwitchApplication.FindingAction) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.FindingAction);
            }
            return null;
        }
    }
}
