//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    /// <summary>
    /// Defines the names of the application permissions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static class Permissions
    {
        /// <summary>
        /// Provides the ability to manage security for the application.
        /// </summary>
        public const string SecurityAdministration = global::Microsoft.LightSwitch.Security.ApplicationPermissions.SecurityAdministration;
        /// <summary>
        /// Can Edit Audit Auditors
        /// </summary>
        public const string CanEditAuditAuditors = "LightSwitchApplication:CanEditAuditAuditors";
        /// <summary>
        /// Can Edit Audit Findings
        /// </summary>
        public const string CanEditAuditFindings = "LightSwitchApplication:CanEditAuditFindings";
        /// <summary>
        /// Can Edit Auditors
        /// </summary>
        public const string CanEditAuditors = "LightSwitchApplication:CanEditAuditors";
        /// <summary>
        /// Can Edit Audits
        /// </summary>
        public const string CanEditAudits = "LightSwitchApplication:CanEditAudits";
        /// <summary>
        /// Can Edit Audit Statuses
        /// </summary>
        public const string CanEditAuditStatuses = "LightSwitchApplication:CanEditAuditStatuses";
        /// <summary>
        /// Can Edit Audit Types
        /// </summary>
        public const string CanEditAuditTypes = "LightSwitchApplication:CanEditAuditTypes";
        /// <summary>
        /// Can Edit Employees
        /// </summary>
        public const string CanEditEmployees = "LightSwitchApplication:CanEditEmployees";
        /// <summary>
        /// Can Edit Finding Actions
        /// </summary>
        public const string CanEditFindingActions = "LightSwitchApplication:CanEditFindingActions";

        /// <summary>
        /// Gets all permissions defined for the application.  This includes system and user-defined permissions.
        /// </summary>
        public static global::System.Collections.ObjectModel.ReadOnlyCollection<string> AllPermissions { get { return global::Microsoft.LightSwitch.Security.ApplicationPermissions.AllPermissions; } }
    }
}
