//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.ApplicationData>
    {
    
        public ApplicationDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).ApplicationData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.ApplicationData>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.AuditFinding> MyAssignedAuditFindings()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.AuditFinding> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.AuditFinding>("AuditFindings");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.FindingAction> MyAuditFindingActions()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.FindingAction> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.FindingAction>("FindingActions");
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.AuditAuditor))
            {
                return new global::LightSwitchApplication.Implementation.AuditAuditor();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.AuditFinding))
            {
                return new global::LightSwitchApplication.Implementation.AuditFinding();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Auditor))
            {
                return new global::LightSwitchApplication.Implementation.Auditor();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Audit))
            {
                return new global::LightSwitchApplication.Implementation.Audit();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.AuditStatus))
            {
                return new global::LightSwitchApplication.Implementation.AuditStatus();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.AuditType))
            {
                return new global::LightSwitchApplication.Implementation.AuditType();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.FindingAction))
            {
                return new global::LightSwitchApplication.Implementation.FindingAction();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.ApplicationData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.ApplicationData(this.GetEntityConnectionString(
                "_IntrinsicData",
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.AuditAuditor))
            {
                return new global::LightSwitchApplication.Implementation.AuditAuditor();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AuditFinding))
            {
                return new global::LightSwitchApplication.Implementation.AuditFinding();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Auditor))
            {
                return new global::LightSwitchApplication.Implementation.Auditor();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Audit))
            {
                return new global::LightSwitchApplication.Implementation.Audit();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AuditStatus))
            {
                return new global::LightSwitchApplication.Implementation.AuditStatus();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AuditType))
            {
                return new global::LightSwitchApplication.Implementation.AuditType();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.FindingAction))
            {
                return new global::LightSwitchApplication.Implementation.FindingAction();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.AuditAuditor) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AuditAuditor);
            }
            if (typeof(global::LightSwitchApplication.AuditFinding) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AuditFinding);
            }
            if (typeof(global::LightSwitchApplication.Auditor) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Auditor);
            }
            if (typeof(global::LightSwitchApplication.Audit) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Audit);
            }
            if (typeof(global::LightSwitchApplication.AuditStatus) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AuditStatus);
            }
            if (typeof(global::LightSwitchApplication.AuditType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AuditType);
            }
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            if (typeof(global::LightSwitchApplication.FindingAction) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.FindingAction);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AuditAuditor :
        global::LightSwitchApplication.AuditAuditor.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AuditAuditor.DetailsClass.IImplementation.Audit
        {
            get
            {
                return this.Audit;
            }
            set
            {
                this.Audit = (global::LightSwitchApplication.Implementation.Audit)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Audit");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AuditAuditor.DetailsClass.IImplementation.Auditor
        {
            get
            {
                return this.Auditor;
            }
            set
            {
                this.Auditor = (global::LightSwitchApplication.Implementation.Auditor)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Auditor");
                }
            }
        }
        
        partial void OnAuditAuditor_AuditChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Audit");
            }
        }
        
        partial void OnAuditAuditor_AuditorChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Auditor");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AuditFinding :
        global::LightSwitchApplication.AuditFinding.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AuditFinding.DetailsClass.IImplementation.AssignedTo
        {
            get
            {
                return this.AssignedTo;
            }
            set
            {
                this.AssignedTo = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("AssignedTo");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.AuditFinding.DetailsClass.IImplementation.FindingAction
        {
            get
            {
                return this.FindingAction;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AuditFinding.DetailsClass.IImplementation.Audit
        {
            get
            {
                return this.Audit;
            }
            set
            {
                this.Audit = (global::LightSwitchApplication.Implementation.Audit)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Audit");
                }
            }
        }
        
        partial void OnAuditFinding_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("AssignedTo");
            }
        }
        
        partial void OnAuditFinding_AuditChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Audit");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Auditor :
        global::LightSwitchApplication.Auditor.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Auditor.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Employee");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Auditor.DetailsClass.IImplementation.AuditAuditors
        {
            get
            {
                return this.AuditAuditors;
            }
        }
        
        partial void OnAuditor_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Employee");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Audit :
        global::LightSwitchApplication.Audit.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Audit.DetailsClass.IImplementation.AuditType
        {
            get
            {
                return this.AuditType;
            }
            set
            {
                this.AuditType = (global::LightSwitchApplication.Implementation.AuditType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("AuditType");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Audit.DetailsClass.IImplementation.AuditStatus
        {
            get
            {
                return this.AuditStatus;
            }
            set
            {
                this.AuditStatus = (global::LightSwitchApplication.Implementation.AuditStatus)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("AuditStatus");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Audit.DetailsClass.IImplementation.AuditAuditors
        {
            get
            {
                return this.AuditAuditors;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Audit.DetailsClass.IImplementation.AuditFindings
        {
            get
            {
                return this.AuditFindings;
            }
        }
        
        partial void OnAuditType_AuditChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("AuditType");
            }
        }
        
        partial void OnAuditStatus_AuditChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("AuditStatus");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AuditStatus :
        global::LightSwitchApplication.AuditStatus.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.AuditStatus.DetailsClass.IImplementation.Audits
        {
            get
            {
                return this.Audits;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AuditType :
        global::LightSwitchApplication.AuditType.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.AuditType.DetailsClass.IImplementation.Audits
        {
            get
            {
                return this.Audits;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.Auditors
        {
            get
            {
                return this.Auditors;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.AuditFindings
        {
            get
            {
                return this.AuditFindings;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.FindingAction
        {
            get
            {
                return this.FindingAction;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class FindingAction :
        global::LightSwitchApplication.FindingAction.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.FindingAction.DetailsClass.IImplementation.AssignedTo
        {
            get
            {
                return this.AssignedTo;
            }
            set
            {
                this.AssignedTo = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("AssignedTo");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.FindingAction.DetailsClass.IImplementation.AuditFinding
        {
            get
            {
                return this.AuditFinding;
            }
            set
            {
                this.AuditFinding = (global::LightSwitchApplication.Implementation.AuditFinding)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("AuditFinding");
                }
            }
        }
        
        partial void OnIssueAction_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("AssignedTo");
            }
        }
        
        partial void OnIssueAction_AuditFindingChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("AuditFinding");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

