

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class Auditor : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Auditor entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Auditor()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Auditor(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Auditor> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Auditor.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Auditor_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Auditor_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Auditor.DetailsClass.GetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Auditor.DetailsClass.SetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateTrained
        {
            get
            {
                return global::LightSwitchApplication.Auditor.DetailsClass.GetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.DateTrained);
            }
            set
            {
                global::LightSwitchApplication.Auditor.DetailsClass.SetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.DateTrained, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateTrained_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateTrained_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateTrained_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool CurrentAuditor
        {
            get
            {
                return global::LightSwitchApplication.Auditor.DetailsClass.GetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.CurrentAuditor);
            }
            set
            {
                global::LightSwitchApplication.Auditor.DetailsClass.SetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.CurrentAuditor, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CurrentAuditor_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CurrentAuditor_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CurrentAuditor_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.Auditor.DetailsClass.GetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.Auditor.DetailsClass.GetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.Auditor.DetailsClass.GetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.Auditor.DetailsClass.GetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Auditor.DetailsClass.GetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Auditor.DetailsClass.SetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Employee Employee
        {
            get
            {
                return global::LightSwitchApplication.Auditor.DetailsClass.GetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.Employee);
            }
            set
            {
                global::LightSwitchApplication.Auditor.DetailsClass.SetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.Employee, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Employee_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Employee_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Employee_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.AuditAuditor> AuditAuditors
        {
            get
            {
                return global::LightSwitchApplication.Auditor.DetailsClass.GetValue(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.AuditAuditors);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.AuditAuditor> AuditAuditorsQuery
        {
            get
            {
                return global::LightSwitchApplication.Auditor.DetailsClass.GetQuery(this, global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.AuditAuditors);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Auditor,
                global::LightSwitchApplication.Auditor.DetailsClass,
                global::LightSwitchApplication.Auditor.DetailsClass.IImplementation,
                global::LightSwitchApplication.Auditor.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass>.Entry
                __AuditorEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass>.Entry(
                    global::LightSwitchApplication.Auditor.DetailsClass.__Auditor_CreateNew,
                    global::LightSwitchApplication.Auditor.DetailsClass.__Auditor_Created,
                    global::LightSwitchApplication.Auditor.DetailsClass.__Auditor_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Auditor __Auditor_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Auditor> es)
            {
                return new global::LightSwitchApplication.Auditor(es);
            }
            private static void __Auditor_Created(global::LightSwitchApplication.Auditor e)
            {
                e.Auditor_Created();
            }
            private static bool __Auditor_AllowSaveWithErrors(global::LightSwitchApplication.Auditor e)
            {
                bool result = false;
                e.Auditor_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Auditor.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTime>> DateTrained
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.DateTrained) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, bool> CurrentAuditor
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.CurrentAuditor) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::LightSwitchApplication.Employee> Employee
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.Employee) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::LightSwitchApplication.Employee>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::LightSwitchApplication.AuditAuditor> AuditAuditors
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.AuditAuditors) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::LightSwitchApplication.AuditAuditor>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new global::System.Nullable<global::System.DateTime> DateTrained { get; set; }
                new bool CurrentAuditor { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Employee { get; set; }
                new global::System.Collections.IEnumerable AuditAuditors { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Auditor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, int>.Data> c, global::LightSwitchApplication.Auditor.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Auditor e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Auditor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Auditor e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateTrained = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateTrained",
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._DateTrained_Stub,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._DateTrained_ComputeIsReadOnly,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._DateTrained_Validate,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._DateTrained_GetImplementationValue,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._DateTrained_SetImplementationValue,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._DateTrained_OnValueChanged);
                private static void _DateTrained_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Auditor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Auditor.DetailsClass d, object sf)
                {
                    c(d, ref d._DateTrained, sf);
                }
                private static bool _DateTrained_ComputeIsReadOnly(global::LightSwitchApplication.Auditor e)
                {
                    bool result = false;
                    e.DateTrained_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateTrained_Validate(global::LightSwitchApplication.Auditor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateTrained_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateTrained_GetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d)
                {
                    return d.ImplementationEntity.DateTrained;
                }
                private static void _DateTrained_SetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateTrained = global::LightSwitchApplication.Auditor.DetailsClass.TruncateDate(v);
                }
                private static void _DateTrained_OnValueChanged(global::LightSwitchApplication.Auditor e)
                {
                    e.DateTrained_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, bool>.Entry
                    CurrentAuditor = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, bool>.Entry(
                        "CurrentAuditor",
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._CurrentAuditor_Stub,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._CurrentAuditor_ComputeIsReadOnly,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._CurrentAuditor_Validate,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._CurrentAuditor_GetImplementationValue,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._CurrentAuditor_SetImplementationValue,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._CurrentAuditor_OnValueChanged);
                private static void _CurrentAuditor_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Auditor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, bool>.Data> c, global::LightSwitchApplication.Auditor.DetailsClass d, object sf)
                {
                    c(d, ref d._CurrentAuditor, sf);
                }
                private static bool _CurrentAuditor_ComputeIsReadOnly(global::LightSwitchApplication.Auditor e)
                {
                    bool result = false;
                    e.CurrentAuditor_IsReadOnly(ref result);
                    return result;
                }
                private static void _CurrentAuditor_Validate(global::LightSwitchApplication.Auditor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CurrentAuditor_Validate(r);
                }
                private static bool _CurrentAuditor_GetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d)
                {
                    return d.ImplementationEntity.CurrentAuditor;
                }
                private static void _CurrentAuditor_SetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.CurrentAuditor = v;
                }
                private static void _CurrentAuditor_OnValueChanged(global::LightSwitchApplication.Auditor e)
                {
                    e.CurrentAuditor_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Auditor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, string>.Data> c, global::LightSwitchApplication.Auditor.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.Auditor e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.Auditor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.Auditor e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Auditor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Auditor.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.Auditor e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.Auditor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.Auditor e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Auditor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, string>.Data> c, global::LightSwitchApplication.Auditor.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.Auditor e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.Auditor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.Auditor e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Auditor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Auditor.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.Auditor e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.Auditor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.Auditor e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Auditor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Auditor.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Auditor e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Auditor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Auditor e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::LightSwitchApplication.Employee>.Entry
                    Employee = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::LightSwitchApplication.Employee>.Entry(
                        "Employee",
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Employee_Stub,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Employee_ComputeIsReadOnly,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Employee_Validate,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Employee_GetCoreImplementationValue,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Employee_GetImplementationValue,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Employee_SetImplementationValue,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Employee_Refresh,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._Employee_OnValueChanged);
                private static void _Employee_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Auditor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::LightSwitchApplication.Employee>.Data> c, global::LightSwitchApplication.Auditor.DetailsClass d, object sf)
                {
                    c(d, ref d._Employee, sf);
                }
                private static bool _Employee_ComputeIsReadOnly(global::LightSwitchApplication.Auditor e)
                {
                    bool result = false;
                    e.Employee_IsReadOnly(ref result);
                    return result;
                }
                private static void _Employee_Validate(global::LightSwitchApplication.Auditor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Employee_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Employee_GetCoreImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d)
                {
                    return d.ImplementationEntity.Employee;
                }
                private static global::LightSwitchApplication.Employee _Employee_GetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Employee, global::LightSwitchApplication.Employee.DetailsClass>(global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.Employee, ref d._Employee);
                }
                private static void _Employee_SetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass d, global::LightSwitchApplication.Employee v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.Employee, ref d._Employee, (i, ev) => i.Employee = ev, v);
                }
                private static void _Employee_Refresh(global::LightSwitchApplication.Auditor.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.Employee, ref d._Employee);
                }
                private static void _Employee_OnValueChanged(global::LightSwitchApplication.Auditor e)
                {
                    e.Employee_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::LightSwitchApplication.AuditAuditor>.Entry
                    AuditAuditors = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::LightSwitchApplication.AuditAuditor>.Entry(
                        "AuditAuditors",
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._AuditAuditors_Stub,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._AuditAuditors_GetReferencedEntities,
                        global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties._AuditAuditors_GetEntityCollection);
                private static void _AuditAuditors_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Auditor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::LightSwitchApplication.AuditAuditor>.Data> c, global::LightSwitchApplication.Auditor.DetailsClass d, object sf)
                {
                    c(d, ref d._AuditAuditors, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.AuditAuditor> _AuditAuditors_GetReferencedEntities(global::LightSwitchApplication.Auditor.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.AuditAuditor, global::LightSwitchApplication.AuditAuditor.DetailsClass>(global::LightSwitchApplication.Auditor.DetailsClass.PropertySetProperties.AuditAuditors, ref d._AuditAuditors);
                }
                private static global::System.Collections.IEnumerable _AuditAuditors_GetEntityCollection(global::LightSwitchApplication.Auditor.DetailsClass d)
                {
                    return d.ImplementationEntity.AuditAuditors;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateTrained;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, bool>.Data _CurrentAuditor;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::LightSwitchApplication.Employee>.Data _Employee;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Auditor, global::LightSwitchApplication.Auditor.DetailsClass, global::LightSwitchApplication.AuditAuditor>.Data _AuditAuditors;
            
        }
    
        #endregion
    }
    
    #endregion
}
